package com.refermecommunity.portal.controller;

import com.refermecommunity.portal.model.User;
import com.refermecommunity.portal.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String firstname
            , @RequestParam String lastName, @RequestParam String email, @RequestParam String password, @RequestParam String company,
            @RequestParam String designation, @RequestParam String city, @RequestParam String country, @RequestParam String phone,
            @RequestParam(required=false) byte[] resume) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setFirstName(firstname);
        n.setLastName(lastName);
        n.setEmail(email);
        n.setPassword(password);
        n.setCompany(company);
        n.setDesignation(designation);
        n.setCity(city);
        n.setCountry(country);
        n.setPhone(phone);
        n.setResume(resume);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}